# Fish completion for openmeteo CLI
# Place in ~/.config/fish/completions/openmeteo.fish or
# $(brew --prefix)/share/fish/vendor_completions.d/openmeteo.fish

# Disable file completions globally
complete -c openmeteo -f

# All subcommands — used to guard top-level completions
set -l subcmds weather geo history ensemble climate marine air-quality flood elevation satellite config help

# ---------- Subcommands (no subcommand given yet) ----------

complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -a weather     -d 'Weather forecast (up to 16 days)'
complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -a geo         -d 'Geocoding (search locations by name)'
complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -a history     -d 'Historical weather data (from 1940)'
complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -a ensemble    -d 'Ensemble model forecasts'
complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -a climate     -d 'Climate change projections (1950-2050)'
complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -a marine      -d 'Marine / wave forecasts'
complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -a air-quality -d 'Air quality & pollen forecasts'
complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -a flood       -d 'River discharge / flood forecasts'
complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -a elevation   -d 'Terrain elevation lookup'
complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -a satellite   -d 'Satellite solar radiation data'
complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -a config      -d 'Manage configuration file'
complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -a help        -d 'Show help'

# ---------- Global options (before subcommand) ----------

complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -l api-key   -r -d 'OpenMeteo API key'
complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -l human        -d 'Human-friendly output (override config)'
complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -l porcelain    -d 'Machine-parseable output'
complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -l llm          -d 'Compact TSV output for AI agents'
complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -l raw          -d 'Raw JSON output'
complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -l verbose      -d 'Show resolved locations and request URLs'
complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -l help         -d 'Show help'
complete -c openmeteo -n "not __fish_seen_subcommand_from $subcmds" -l version      -d 'Show version'

# ---------- weather ----------

complete -c openmeteo -n '__fish_seen_subcommand_from weather' -a help                -d 'Show weather help'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l lat               -r -d 'Latitude'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l lon               -r -d 'Longitude'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l city              -r -d 'City name'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l country           -r -d 'Country code (ISO 3166-1 alpha-2)'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l current              -d 'Include current conditions'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l daily                -d 'Include daily forecast'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l hourly               -d 'Include hourly forecast'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l forecast-days      -r -d 'Forecast days (0-16)'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l forecast-since     -r -d 'Start from day N (1=today)'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l past-days          -r -d 'Past days (0-92)'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l start-date         -r -d 'Start date (YYYY-MM-DD)'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l end-date           -r -d 'End date (YYYY-MM-DD)'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l hourly-params      -r -d 'Hourly variables'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l daily-params       -r -d 'Daily variables'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l current-params     -r -d 'Current variables'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l temperature-unit   -r -d 'Temperature unit' -a 'celsius fahrenheit'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l wind-speed-unit    -r -d 'Wind speed unit' -a 'kmh ms mph kn'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l precipitation-unit -r -d 'Precipitation unit' -a 'mm inch'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l timezone           -r -d 'Timezone'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l model              -r -d 'Weather model'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l api-key            -r -d 'API key'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l human                 -d 'Human-friendly output'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l porcelain             -d 'Machine-parseable output'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l llm                   -d 'Compact TSV output'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l raw                   -d 'Raw JSON output'
complete -c openmeteo -n '__fish_seen_subcommand_from weather' -l help                  -d 'Show help'

# ---------- geo ----------

complete -c openmeteo -n '__fish_seen_subcommand_from geo' -a help              -d 'Show geo help'
complete -c openmeteo -n '__fish_seen_subcommand_from geo' -l search          -r -d 'Search query'
complete -c openmeteo -n '__fish_seen_subcommand_from geo' -l count           -r -d 'Number of results'
complete -c openmeteo -n '__fish_seen_subcommand_from geo' -l language        -r -d 'Result language'
complete -c openmeteo -n '__fish_seen_subcommand_from geo' -l country         -r -d 'Country filter'
complete -c openmeteo -n '__fish_seen_subcommand_from geo' -l api-key         -r -d 'API key'
complete -c openmeteo -n '__fish_seen_subcommand_from geo' -l human              -d 'Human-friendly output'
complete -c openmeteo -n '__fish_seen_subcommand_from geo' -l porcelain          -d 'Machine-parseable output'
complete -c openmeteo -n '__fish_seen_subcommand_from geo' -l llm                -d 'Compact TSV output'
complete -c openmeteo -n '__fish_seen_subcommand_from geo' -l raw                -d 'Raw JSON output'
complete -c openmeteo -n '__fish_seen_subcommand_from geo' -l help               -d 'Show help'

# ---------- history ----------

complete -c openmeteo -n '__fish_seen_subcommand_from history' -a help                -d 'Show history help'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l lat               -r -d 'Latitude'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l lon               -r -d 'Longitude'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l city              -r -d 'City name'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l country           -r -d 'Country code'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l start-date        -r -d 'Start date (YYYY-MM-DD)'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l end-date          -r -d 'End date (YYYY-MM-DD)'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l hourly-params     -r -d 'Hourly variables'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l daily-params      -r -d 'Daily variables'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l temperature-unit  -r -d 'Temperature unit' -a 'celsius fahrenheit'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l wind-speed-unit   -r -d 'Wind speed unit' -a 'kmh ms mph kn'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l precipitation-unit -r -d 'Precipitation unit' -a 'mm inch'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l timezone          -r -d 'Timezone'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l model             -r -d 'Reanalysis model'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l cell-selection    -r -d 'Grid cell selection' -a 'land sea nearest'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l api-key           -r -d 'API key'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l human                -d 'Human-friendly output'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l porcelain            -d 'Machine-parseable output'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l llm                  -d 'Compact TSV output'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l raw                  -d 'Raw JSON output'
complete -c openmeteo -n '__fish_seen_subcommand_from history' -l help                 -d 'Show help'

# ---------- ensemble ----------

complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -a help                 -d 'Show ensemble help'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l lat                -r -d 'Latitude'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l lon                -r -d 'Longitude'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l city               -r -d 'City name'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l country            -r -d 'Country code'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l models             -r -d 'Ensemble models'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l hourly-params      -r -d 'Hourly variables'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l daily-params       -r -d 'Daily variables'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l forecast-days      -r -d 'Forecast days (0-35)'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l forecast-since     -r -d 'Start from day N (1=today)'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l past-days          -r -d 'Past days'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l start-date         -r -d 'Start date'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l end-date           -r -d 'End date'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l temperature-unit   -r -d 'Temperature unit' -a 'celsius fahrenheit'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l wind-speed-unit    -r -d 'Wind speed unit' -a 'kmh ms mph kn'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l precipitation-unit -r -d 'Precipitation unit' -a 'mm inch'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l timezone           -r -d 'Timezone'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l cell-selection     -r -d 'Grid cell selection' -a 'land sea nearest'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l api-key            -r -d 'API key'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l human                 -d 'Human-friendly output'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l porcelain             -d 'Machine-parseable output'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l llm                   -d 'Compact TSV output'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l raw                   -d 'Raw JSON output'
complete -c openmeteo -n '__fish_seen_subcommand_from ensemble' -l help                  -d 'Show help'

# ---------- climate ----------

complete -c openmeteo -n '__fish_seen_subcommand_from climate' -a help                  -d 'Show climate help'
complete -c openmeteo -n '__fish_seen_subcommand_from climate' -l lat                 -r -d 'Latitude'
complete -c openmeteo -n '__fish_seen_subcommand_from climate' -l lon                 -r -d 'Longitude'
complete -c openmeteo -n '__fish_seen_subcommand_from climate' -l city                -r -d 'City name'
complete -c openmeteo -n '__fish_seen_subcommand_from climate' -l country             -r -d 'Country code'
complete -c openmeteo -n '__fish_seen_subcommand_from climate' -l start-date          -r -d 'Start date (from 1950)'
complete -c openmeteo -n '__fish_seen_subcommand_from climate' -l end-date            -r -d 'End date (up to 2050)'
complete -c openmeteo -n '__fish_seen_subcommand_from climate' -l models              -r -d 'Climate models'
complete -c openmeteo -n '__fish_seen_subcommand_from climate' -l daily-params        -r -d 'Daily variables'
complete -c openmeteo -n '__fish_seen_subcommand_from climate' -l temperature-unit    -r -d 'Temperature unit' -a 'celsius fahrenheit'
complete -c openmeteo -n '__fish_seen_subcommand_from climate' -l wind-speed-unit     -r -d 'Wind speed unit' -a 'kmh ms mph kn'
complete -c openmeteo -n '__fish_seen_subcommand_from climate' -l precipitation-unit  -r -d 'Precipitation unit' -a 'mm inch'
complete -c openmeteo -n '__fish_seen_subcommand_from climate' -l cell-selection      -r -d 'Grid cell selection' -a 'land sea nearest'
complete -c openmeteo -n '__fish_seen_subcommand_from climate' -l disable-bias-correction -d 'Disable statistical downscaling'
complete -c openmeteo -n '__fish_seen_subcommand_from climate' -l api-key             -r -d 'API key'
complete -c openmeteo -n '__fish_seen_subcommand_from climate' -l human                  -d 'Human-friendly output'
complete -c openmeteo -n '__fish_seen_subcommand_from climate' -l porcelain              -d 'Machine-parseable output'
complete -c openmeteo -n '__fish_seen_subcommand_from climate' -l llm                    -d 'Compact TSV output'
complete -c openmeteo -n '__fish_seen_subcommand_from climate' -l raw                    -d 'Raw JSON output'
complete -c openmeteo -n '__fish_seen_subcommand_from climate' -l help                   -d 'Show help'

# ---------- marine ----------

complete -c openmeteo -n '__fish_seen_subcommand_from marine' -a help                 -d 'Show marine help'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l lat                -r -d 'Latitude'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l lon                -r -d 'Longitude'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l city               -r -d 'City name'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l country            -r -d 'Country code'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l current               -d 'Include current conditions'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l forecast-days       -r -d 'Forecast days (0-16)'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l forecast-since      -r -d 'Start from day N (1=today)'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l past-days           -r -d 'Past days (0-92)'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l hourly-params       -r -d 'Hourly variables'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l daily-params        -r -d 'Daily variables'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l current-params      -r -d 'Current variables'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l length-unit         -r -d 'Length unit' -a 'metric imperial'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l wind-speed-unit     -r -d 'Wind speed unit' -a 'kmh ms mph kn'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l timezone            -r -d 'Timezone'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l model               -r -d 'Marine model'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l cell-selection      -r -d 'Grid cell selection' -a 'land sea nearest'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l start-date          -r -d 'Start date'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l end-date            -r -d 'End date'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l api-key             -r -d 'API key'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l human                  -d 'Human-friendly output'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l porcelain              -d 'Machine-parseable output'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l llm                    -d 'Compact TSV output'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l raw                    -d 'Raw JSON output'
complete -c openmeteo -n '__fish_seen_subcommand_from marine' -l help                   -d 'Show help'

# ---------- air-quality ----------

complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -a help                   -d 'Show air-quality help'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l lat                  -r -d 'Latitude'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l lon                  -r -d 'Longitude'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l city                 -r -d 'City name'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l country              -r -d 'Country code'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l current                 -d 'Include current conditions'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l forecast-days         -r -d 'Forecast days (0-7)'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l forecast-since        -r -d 'Start from day N (1=today)'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l past-days             -r -d 'Past days (0-92)'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l hourly-params         -r -d 'Hourly variables'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l daily-params          -r -d 'Daily variables'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l current-params        -r -d 'Current variables'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l domains               -r -d 'Model domain' -a 'auto cams_europe cams_global'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l timezone              -r -d 'Timezone'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l cell-selection        -r -d 'Grid cell selection' -a 'land sea nearest'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l start-date            -r -d 'Start date'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l end-date              -r -d 'End date'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l api-key               -r -d 'API key'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l human                    -d 'Human-friendly output'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l porcelain                -d 'Machine-parseable output'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l llm                      -d 'Compact TSV output'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l raw                      -d 'Raw JSON output'
complete -c openmeteo -n '__fish_seen_subcommand_from air-quality' -l help                     -d 'Show help'

# ---------- flood ----------

complete -c openmeteo -n '__fish_seen_subcommand_from flood' -a help                -d 'Show flood help'
complete -c openmeteo -n '__fish_seen_subcommand_from flood' -l lat               -r -d 'Latitude'
complete -c openmeteo -n '__fish_seen_subcommand_from flood' -l lon               -r -d 'Longitude'
complete -c openmeteo -n '__fish_seen_subcommand_from flood' -l city              -r -d 'City name'
complete -c openmeteo -n '__fish_seen_subcommand_from flood' -l country           -r -d 'Country code'
complete -c openmeteo -n '__fish_seen_subcommand_from flood' -l forecast-days     -r -d 'Forecast days (0-210)'
complete -c openmeteo -n '__fish_seen_subcommand_from flood' -l forecast-since    -r -d 'Start from day N (1=today)'
complete -c openmeteo -n '__fish_seen_subcommand_from flood' -l past-days         -r -d 'Past days'
complete -c openmeteo -n '__fish_seen_subcommand_from flood' -l daily-params      -r -d 'Daily variables'
complete -c openmeteo -n '__fish_seen_subcommand_from flood' -l model             -r -d 'GloFAS model'
complete -c openmeteo -n '__fish_seen_subcommand_from flood' -l cell-selection    -r -d 'Grid cell selection' -a 'land sea nearest'
complete -c openmeteo -n '__fish_seen_subcommand_from flood' -l ensemble             -d 'Include all 50 ensemble members'
complete -c openmeteo -n '__fish_seen_subcommand_from flood' -l start-date        -r -d 'Start date'
complete -c openmeteo -n '__fish_seen_subcommand_from flood' -l end-date          -r -d 'End date'
complete -c openmeteo -n '__fish_seen_subcommand_from flood' -l api-key           -r -d 'API key'
complete -c openmeteo -n '__fish_seen_subcommand_from flood' -l human                -d 'Human-friendly output'
complete -c openmeteo -n '__fish_seen_subcommand_from flood' -l porcelain            -d 'Machine-parseable output'
complete -c openmeteo -n '__fish_seen_subcommand_from flood' -l llm                  -d 'Compact TSV output'
complete -c openmeteo -n '__fish_seen_subcommand_from flood' -l raw                  -d 'Raw JSON output'
complete -c openmeteo -n '__fish_seen_subcommand_from flood' -l help                 -d 'Show help'

# ---------- elevation ----------

complete -c openmeteo -n '__fish_seen_subcommand_from elevation' -a help              -d 'Show elevation help'
complete -c openmeteo -n '__fish_seen_subcommand_from elevation' -l lat             -r -d 'Latitude (comma-separated for multiple)'
complete -c openmeteo -n '__fish_seen_subcommand_from elevation' -l lon             -r -d 'Longitude (comma-separated for multiple)'
complete -c openmeteo -n '__fish_seen_subcommand_from elevation' -l city            -r -d 'City name'
complete -c openmeteo -n '__fish_seen_subcommand_from elevation' -l country         -r -d 'Country code'
complete -c openmeteo -n '__fish_seen_subcommand_from elevation' -l api-key         -r -d 'API key'
complete -c openmeteo -n '__fish_seen_subcommand_from elevation' -l human              -d 'Human-friendly output'
complete -c openmeteo -n '__fish_seen_subcommand_from elevation' -l porcelain          -d 'Machine-parseable output'
complete -c openmeteo -n '__fish_seen_subcommand_from elevation' -l llm                -d 'Compact TSV output'
complete -c openmeteo -n '__fish_seen_subcommand_from elevation' -l raw                -d 'Raw JSON output'
complete -c openmeteo -n '__fish_seen_subcommand_from elevation' -l help               -d 'Show help'

# ---------- satellite ----------

complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -a help                  -d 'Show satellite help'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l lat                 -r -d 'Latitude'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l lon                 -r -d 'Longitude'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l city                -r -d 'City name'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l country             -r -d 'Country code'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l forecast-days       -r -d 'Days (0-1)'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l past-days           -r -d 'Past days of satellite archive'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l hourly-params       -r -d 'Hourly variables'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l daily-params        -r -d 'Daily variables'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l model               -r -d 'Satellite source/NWP model'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l timezone            -r -d 'Timezone'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l cell-selection      -r -d 'Grid cell selection' -a 'land sea nearest'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l tilt                -r -d 'Panel tilt in degrees (0-90)'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l azimuth             -r -d 'Panel azimuth in degrees'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l temporal-resolution -r -d 'Resolution' -a 'hourly native'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l start-date          -r -d 'Start date'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l end-date            -r -d 'End date'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l api-key             -r -d 'API key'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l human                  -d 'Human-friendly output'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l porcelain              -d 'Machine-parseable output'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l llm                    -d 'Compact TSV output'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l raw                    -d 'Raw JSON output'
complete -c openmeteo -n '__fish_seen_subcommand_from satellite' -l help                   -d 'Show help'

# ---------- config ----------

complete -c openmeteo -n '__fish_seen_subcommand_from config' -a help  -d 'Show config help'
complete -c openmeteo -n '__fish_seen_subcommand_from config' -a init  -d 'Create config file with defaults'
complete -c openmeteo -n '__fish_seen_subcommand_from config' -a show  -d 'Show current configuration'
complete -c openmeteo -n '__fish_seen_subcommand_from config' -a path  -d 'Print config file path'
complete -c openmeteo -n '__fish_seen_subcommand_from config' -a set   -d 'Set a configuration value'
complete -c openmeteo -n '__fish_seen_subcommand_from config' -a unset -d 'Remove a configuration value'
complete -c openmeteo -n '__fish_seen_subcommand_from config' -a get   -d 'Get a single configuration value'
